# Imports 

In [1]:
import numpy as np
from tqdm.notebook import tqdm
import time

In [2]:
# example of a for loop 
for i in tqdm(range(101)):
    time.sleep(0.1)
    print(f"\r{i}",end="")

  0%|          | 0/101 [00:00<?, ?it/s]

100

## Create numpy array

In [3]:
np.array([1,2,3,7])

array([1, 2, 3, 7])

## create numpy matrix

In [4]:
numpy_matrix = np.array([[1,2],[2,1]])

In [5]:
numpy_matrix

array([[1, 2],
       [2, 1]])

## Using arange to create arrays.

In [6]:
np.arange(3,7,2)

array([3, 5])

## Using linspace

In [7]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [8]:
np.linspace(2.0,3.0,num=2,endpoint=False)

array([2. , 2.5])

In [9]:
np.linspace(2.0,3.0,num=2)

array([2., 3.])

In [10]:
# shape to tell col x rows
help(np.shape)
# arr.size to show how many elements 


Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    len
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



# Using repeat 

In [11]:
x = np.array([1,2,3,4])

In [12]:
np.repeat(x,1)

array([1, 2, 3, 4])

In [13]:
np.repeat(x,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
# np.repeat(x,1,axis=2)

In [16]:
np.repeat(numpy_matrix,1,axis=1)

array([[1, 2],
       [2, 1]])

In [17]:
np.repeat(numpy_matrix,1,axis=0)

array([[1, 2],
       [2, 1]])

# Task

In [18]:
def get_seconed_digit():
    ID = str((input("Enter Your ID Number :\n").split("-"))[1])
    return ID[1]

In [19]:
y = np.arange(21)

In [20]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
y_repeated = np.repeat(y,get_seconed_digit())

Enter Your ID Number :
49-17004


In [ ]:
y_repeated

In [ ]:
y_repeated.shape

In [ ]:
21*7

In [ ]:
y_repeated.size